process.chdir(require('node:path').resolve(__dirname, '..'));
// Local-only VM tests: no Firebase initialization, requests, or live mutations.
const fs = require('fs');
const vm = require('vm');
const assert = require('assert/strict');
const html = fs.readFileSync('index.html', 'utf8');
const names = ['escapeHtml','jsArg','safeAvatar','renderMarkdown','checkIsAdmin','checkIsPostAuthor','isCategoryMod','canDeletePost','renderComments','submitComment','deleteCommentWithCounter','deleteCommentTree','deleteComment','deletePost','verifyChatAccess'];
const extracted = names.map(name => {
 const m = new RegExp('        (?:async )?function '+name+'\\(').exec(html);
 assert(m, name); const rest = html.slice(m.index); if(rest.split('\n')[0].trim().endsWith('}')) return rest.split('\n')[0]; const end = /^        }\s*$/m.exec(rest);
 assert(end, name+' end'); return rest.slice(0,end.index+9);
}).join('\n');
function setup(seed={}) {
 const data = structuredClone(seed), nodes={}, alerts=[], commits=[];
 let nextId=0, beforeCommit=null, queryHook=null, failAt=0, count=0;
 const snap = (path) => ({id:path.split('/')[1],ref:ref(path),exists:!!data[path],data:()=>structuredClone(data[path])});
 const apply=(writes)=>{for(const [type,path,value] of writes){if(type==='delete') delete data[path]; else if(type==='update'){if(!data[path]) throw Error('missing document'); Object.assign(data[path],structuredClone(value));}else data[path]=structuredClone(value);}};
 const ref=path=>({id:path.split('/')[1],path,get:async()=>snap(path),update:async value=>{apply([['update',path,value]]);},delete:async()=>apply([['delete',path]])});
 const db={collection:name=>({doc:id=>ref(name+'/'+(id||'auto'+(++nextId))),where:(key,op,val)=>({get:async()=>{const docs=Object.entries(data).filter(([p,d])=>p.startsWith(name+'/')&&d[key]===val).map(([p])=>snap(p)); const out={docs,size:docs.length}; if(queryHook) {const h=queryHook;queryHook=null;h();} return out;}})}),runTransaction:async fn=>{count++;if(failAt===count) throw Error('simulated interruption'); const writes=[];const tx={get:async r=>snap(r.path),set:(r,v)=>writes.push(['set',r.path,v]),update:(r,v)=>writes.push(['update',r.path,v]),delete:r=>writes.push(['delete',r.path])};await fn(tx);if(beforeCommit) await beforeCommit();const draft=structuredClone(data);try{apply(writes);}catch(e){for(const p of Object.keys(data))delete data[p];Object.assign(data,draft);throw e;}commits.push(writes);}};
 const s={db,console,window:{},URL,document:{getElementById:id=>nodes[id]||(nodes[id]={value:'hello',placeholder:'',textContent:'',classList:{add(){},remove(){},contains(){return false;}}})},currentUser:{uid:'u',displayName:'User',email:'u@example.invalid'},currentUserData:{modCategories:['code']},userRoles:{isAdmin:false,isModerator:true},currentPostId:'p',postDetailGeneration:0,replyingTo:null,submittingComment:false,hasChatAccess:false,chatRoomOpen:false,firebase:{firestore:{FieldValue:{serverTimestamp:()=>123}}},alert:x=>alerts.push(x),confirm:()=>true,showLoginModal(){},showPostDetail(){},loadPosts(){},hidePostDetail(){},loadChatMessages:async()=>{},subscribeToChatMessages(){},marked:{parse:s=>s},escapeHtml:s=>s,getTimeAgo:()=>''};
 vm.createContext(s); vm.runInContext(extracted,s);
 return {s,data,nodes,alerts,commits,setFail:n=>{failAt=n;},setGate:g=>{beforeCommit=g;},setQueryHook:g=>{queryHook=g;}};
}
const post={authorId:'u',category:'code',commentCount:0};
const comment=(authorId='u',parentId)=>({postId:'p',authorId,authorName:authorId,content:'x',...(parentId?{parentId}:{})});
(async()=>{
 let t=setup(); assert(t.s.isCategoryMod('code'));assert(!t.s.isCategoryMod('other'));const comments=[{id:'a',...comment('other')},{id:'b',...comment('other','a')}];let rendered=t.s.renderComments(comments,null,0,'code');assert.equal((rendered.match(/deleteComment\(/g)||[]).length,2);assert(rendered.includes('toggleCommentPin('));rendered=t.s.renderComments(comments,null,0,'other');assert(!rendered.includes('deleteComment('));assert(!rendered.includes('toggleCommentPin(')); console.log('PASS category moderator rendering and recursive category propagation');
 t=setup({'itlab_posts/p':post});let release; t.setGate(()=>new Promise(r=>release=r));const a=t.s.submitComment();await new Promise(r=>setImmediate(r));await t.s.submitComment();assert.equal(t.commits.length,0);release();await a;assert.equal(t.commits.length,1);assert.equal(t.data['itlab_posts/p'].commentCount,1);assert.equal(t.data['itlab_posts/p'].lastCommentId,'auto1');assert.equal(t.data['itlab_comments/auto1'].content,'hello');assert.equal(t.s.submittingComment,false);console.log('PASS duplicate in-flight submission suppressed, atomic create/counter');
 t=setup({'itlab_posts/p':post});t.setFail(1);await t.s.submitComment();assert.equal(t.s.submittingComment,false);assert.equal(t.data['itlab_posts/p'].commentCount,0);await t.s.submitComment();assert.equal(t.data['itlab_posts/p'].commentCount,1);console.log('PASS submission lock released on failure, retry succeeds');
 t=setup({'itlab_posts/p':{...post,commentCount:1},'itlab_comments/a':comment()});await t.s.deleteCommentWithCounter('a','p');await t.s.deleteCommentWithCounter('a','p');assert.equal(t.data['itlab_posts/p'].commentCount,0);assert(!t.data['itlab_comments/a']);console.log('PASS repeated deletion does not double-decrement');
 t=setup({'itlab_posts/p':{...post,commentCount:3},'itlab_comments/a':comment(),'itlab_comments/b':comment('other','a'),'itlab_comments/c':comment('other','b')});t.setFail(2);await t.s.deletePost('p');assert(t.data['itlab_posts/p'].deleting);assert.equal(t.data['itlab_posts/p'].commentCount,2);await t.s.deletePost('p');assert.deepEqual(t.data,{});console.log('PASS interrupted full-post cascade resumes and removes all depths');
 t=setup({'itlab_posts/p':{...post,commentCount:3},'itlab_comments/a':comment(),'itlab_comments/b':comment('other','a'),'itlab_comments/c':comment('other','b')});await t.s.deleteComment('a','p');assert(!t.data['itlab_comments/c']);assert(!t.data['itlab_comments/b']);assert(!t.data['itlab_comments/a']);assert.equal(t.data['itlab_posts/p'].commentCount,0);console.log('PASS recursive comment subtree deletes all descendants');
 t=setup({'itlab_posts/p':{...post,commentCount:1},'itlab_comments/a':comment()});t.setQueryHook(()=>{assert.equal(t.data['itlab_comments/a'].deleting,true);assert.equal(t.data['itlab_comments/a'].deletingBy,'u');});await t.s.deleteComment('a','p');assert(!t.data['itlab_comments/a']);console.log('PASS parent frozen before reply query (actual denial requires emulator rules tests)');
 t=setup({'itlab_posts/p':{...post,commentCount:3},'itlab_comments/a':comment(),'itlab_comments/b':comment('other','a'),'itlab_comments/c':comment('other','b')});t.setFail(2);await t.s.deleteComment('a','p');assert(t.data['itlab_comments/a'].deleting);assert(t.data['itlab_comments/b'].deleting);assert(!t.data['itlab_comments/c']);assert.equal(t.data['itlab_posts/p'].commentCount,2);await t.s.deleteComment('a','p');assert.equal(t.data['itlab_posts/p'].commentCount,0);assert.equal(Object.keys(t.data).length,1);console.log('PASS interrupted recursive comment deletion safely resumes');
 t=setup({'itlab_invitations/CODE':{type:'chat',isUsed:false},'itlab_users/u':{displayName:'User'}});t.s.document.getElementById('chat-invite-code').value='code';await t.s.verifyChatAccess();assert.equal(t.commits.length,1);assert.equal(t.commits[0].length,3);assert(t.data['itlab_invitations/CODE'].isUsed);assert.equal(t.data['itlab_chat_access/u'].usedCode,'CODE');assert(t.data['itlab_users/u'].chatAuthorized);console.log('PASS invitation claim submits all three documents atomically');
 t=setup({'itlab_invitations/CODE':{type:'chat',isUsed:false},'itlab_users/u':{displayName:'User'}});t.s.document.getElementById('chat-invite-code').value='CODE';t.setFail(1);await t.s.verifyChatAccess();assert(!t.data['itlab_invitations/CODE'].isUsed);assert(!t.data['itlab_chat_access/u']);assert(!t.data['itlab_users/u'].chatAuthorized);console.log('PASS failed invitation transaction leaves invitation/profile/access unchanged');
})().catch(e=>{console.error(e);process.exitCode=1;});
