process.chdir(require('node:path').resolve(__dirname, '..'));
const fs=require('fs'),assert=require('assert/strict'),{JSDOM}=require('jsdom');const html=fs.readFileSync('index.html','utf8');
function extract(name){const m=new RegExp('        (?:async )?function '+name+'\\(').exec(html),rest=html.slice(m.index),line=rest.split('\n')[0];if(line.trim().endsWith('}'))return line;return rest.slice(0,/^        }\s*$/m.exec(rest).index+9);}
const dom=new JSDOM('<div id="post-detail-modal"></div><div id="post-detail-content"></div><div id="detail-title"></div><input id="comment-input">',{runScripts:'outside-only'}),w=dom.window;
Object.assign(w,{console,currentUser:{uid:'u',displayName:'User',email:'u@x.invalid'},currentPostId:'a',postDetailGeneration:0,replyingTo:null,submittingComment:false,CATEGORIES:{code:{name:'Code',color:'blue'}},lucide:{createIcons(){}},hljs:{highlightElement(){}},getTimeAgo:()=>'',canEditPost:()=>false,canDeletePost:()=>false,canPinPost:()=>false,canFeaturePost:()=>false,loadPosts(){},showLoginModal(){},firebase:{firestore:{FieldValue:{serverTimestamp:()=>1}}},alert:e=>{throw Error(e)}});
for(const n of ['escapeHtml','jsArg','safeAvatar','renderMarkdown','showPostDetail','hidePostDetail','submitComment'])w.eval(extract(n));
const input=w.document.getElementById('comment-input'),content=w.document.getElementById('post-detail-content'),modal=w.document.getElementById('post-detail-modal');
let gate,queries=0,writes=[],readGate;const post=id=>({exists:true,data:()=>({title:id,content:'content '+id,category:'code',authorName:'User',likedBy:[]})});
w.db={collection:name=>({doc:id=>({id:id||'c',get:async()=>{if(readGate&&id==='a')await readGate;return post(id);}}),where:()=>({get:async()=>{queries++;return {forEach(){}}}})}),runTransaction:async cb=>{const ops=[];await cb({get:async()=>({exists:true,data:()=>({commentCount:0})}),set:(r,d)=>ops.push(d),update(){}});await new Promise(r=>gate=r);writes.push(...ops);}};
(async()=>{
 input.value='old a';const submit=w.submitComment();await new Promise(r=>setImmediate(r));w.hidePostDetail();gate();await submit;assert(modal.classList.contains('hidden'));assert.equal(w.currentPostId,null);assert.equal(input.value,'old a');assert.equal(writes[0].postId,'a');console.log('PASS pending submit then Close does not reopen detail or clear input');
 w.currentPostId='a';modal.classList.remove('hidden');input.value='another a';const submit2=w.submitComment();await new Promise(r=>setImmediate(r));await w.showPostDetail('b');input.value='new b draft';gate();await submit2;assert.equal(w.currentPostId,'b');assert.equal(input.value,'new b draft');assert.equal(writes[1].postId,'a');assert(content.textContent.includes('content b'));console.log('PASS pending A submit then B navigation keeps B draft/view and commits comment only to A');
 let resolve;readGate=new Promise(r=>resolve=r);w.replyingTo={commentId:'old'};const a=w.showPostDetail('a');assert.equal(w.replyingTo,null);await w.showPostDetail('b');const before=content.innerHTML;const count=queries;resolve();await a;assert.equal(content.innerHTML,before);assert.equal(w.currentPostId,'b');assert.equal(queries,count);console.log('PASS late A response cannot replace newer B view or issue stale comments query');
 readGate=new Promise(r=>resolve=r);const a2=w.showPostDetail('a');w.hidePostDetail();resolve();await a2;assert(modal.classList.contains('hidden'));assert.equal(w.currentPostId,null);console.log('PASS detail fetch response after Close does not reopen view');
 w.close();
})().catch(e=>{console.error(e);process.exitCode=1;w.close();});
