import path from 'node:path';
import {fileURLToPath} from 'node:url';
process.chdir(path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..'));
import fs from 'node:fs';
import {initializeTestEnvironment, assertSucceeds, assertFails} from '@firebase/rules-unit-testing';
import {doc,getDoc,getDocs,collection,setDoc,updateDoc,deleteDoc,writeBatch,serverTimestamp} from 'firebase/firestore';
const env=await initializeTestEnvironment({projectId:'demo-jsuitlab',firestore:{host:'127.0.0.1',port:8088,rules:fs.readFileSync('firestore.rules','utf8')}});
const db=uid=>uid?env.authenticatedContext(uid).firestore():env.unauthenticatedContext().firestore();
const user={displayName:'Synthetic User',email:'test@example.invalid',photoURL:'',lastSeen:new Date()};
const post={title:'Test',content:'Test content',category:'tech',tags:[],authorId:'owner',authorName:'Synthetic User',authorAvatar:'',likes:0,likedBy:[],commentCount:0,isPinned:false,isFeatured:false,createdAt:new Date(),updatedAt:new Date()};
const seed=async entries=>env.withSecurityRulesDisabled(async c=>{for(const [path,data] of Object.entries(entries))await setDoc(doc(c.firestore(),path),data);});
let passed=0,failed=0;
async function test(name,fn){try{await fn();console.log('PASS '+name);passed++;}catch(e){console.error('FAIL '+name+' '+e.message);failed++;}}
const yes=assertSucceeds,no=assertFails;
try{
await seed({'itlab_users/owner':user,'itlab_users/other':user,'itlab_users/admin':{...user,isAdmin:true},'itlab_users/mod':{...user,isModerator:true,modCategories:['tech']},'itlab_settings/general':{postPermission:'moderator',chatEnabled:true},'itlab_settings/categories':{categories:['tech']},'itlab_posts/p':post,'itlab_comments/c':{postId:'p',authorId:'owner',content:'hello',createdAt:new Date()},'itlab_chat_messages/m':{userId:'owner',userName:'Synthetic User',content:'hello',createdAt:new Date()}});
await test('profile bootstrap allowed',()=>yes(setDoc(doc(db('new'),'itlab_users/new'),{...user,lastSeen:serverTimestamp()})));
await test('profile bootstrap admin escalation denied',()=>no(setDoc(doc(db('newadmin'),'itlab_users/newadmin'),{...user,lastSeen:serverTimestamp(),isAdmin:true})));
await test('profile bootstrap another user denied',()=>no(setDoc(doc(db('intruder'),'itlab_users/target'),{...user,lastSeen:serverTimestamp()})));
for(const field of ['isAdmin','isModerator','chatAuthorized','modCategories'])await test('profile self '+field+' escalation denied',()=>no(updateDoc(doc(db('owner'),'itlab_users/owner'),{[field]:field==='modCategories'?['tech']:true})));
await test('profile self name edit allowed',()=>yes(updateDoc(doc(db('owner'),'itlab_users/owner'),{displayName:'Changed'})));
await test('profile admin edit allowed',()=>yes(updateDoc(doc(db('admin'),'itlab_users/other'),{displayName:'Admin edited'})));
await test('profile own get allowed',()=>yes(getDoc(doc(db('owner'),'itlab_users/owner'))));
await test('profile stranger get denied',()=>no(getDoc(doc(db('other'),'itlab_users/owner'))));
await test('profile anonymous get denied',()=>no(getDoc(doc(db(),'itlab_users/owner'))));
await test('profile list nonadmin denied',()=>no(getDocs(collection(db('owner'),'itlab_users'))));
await test('profile admin list allowed',()=>yes(getDocs(collection(db('admin'),'itlab_users'))));
for(const path of ['itlab_posts/p','itlab_comments/c','itlab_settings/general','itlab_settings/categories'])await test('public read '+path,()=>yes(getDoc(doc(db(),path))));
await test('settings anonymous list denied',()=>no(getDocs(collection(db(),'itlab_settings'))));
await test('settings ordinary write denied',()=>no(updateDoc(doc(db('owner'),'itlab_settings/general'),{postPermission:'all'})));
const create=uid=>setDoc(doc(db(uid),'itlab_posts/by-'+uid),{...post,authorId:uid,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});
await test('moderator postPermission permits moderator',()=>yes(create('mod')));
await test('moderator postPermission permits admin',()=>yes(create('admin')));
await test('moderator postPermission denies ordinary user',()=>no(create('owner')));
await test('post anonymous create denied',()=>no(create(null)));
await test('postPermission all permits ordinary user',async()=>{await seed({'itlab_settings/general':{postPermission:'all',chatEnabled:true}});await yes(create('owner'));});
for(const uid of ['owner','admin'])await test('post '+uid+' content edit allowed',()=>yes(updateDoc(doc(db(uid),'itlab_posts/p'),{content:'Edited '+uid,lastEditedBy:uid,lastEditedAt:serverTimestamp()})));
await test('post stranger content edit denied',()=>no(updateDoc(doc(db('other'),'itlab_posts/p'),{content:'Intrusion',lastEditedBy:'other',lastEditedAt:serverTimestamp()})));
await test('post author mutation denied',()=>no(updateDoc(doc(db('owner'),'itlab_posts/p'),{authorId:'other'})));
await test('post moderator pin allowed in category',()=>yes(updateDoc(doc(db('mod'),'itlab_posts/p'),{isPinned:true})));
await test('post ordinary user pin denied',()=>no(updateDoc(doc(db('owner'),'itlab_posts/p'),{isPinned:false})));
await test('like own addition allowed',()=>yes(updateDoc(doc(db('other'),'itlab_posts/p'),{likes:1,likedBy:['other']})));
await test('like fabricated user denied',()=>no(updateDoc(doc(db('owner'),'itlab_posts/p'),{likes:2,likedBy:['other','fake']})));
await test('like remove another user denied',()=>no(updateDoc(doc(db('owner'),'itlab_posts/p'),{likes:0,likedBy:[]})));
await test('like count mismatch denied',()=>no(updateDoc(doc(db('owner'),'itlab_posts/p'),{likes:99,likedBy:['other','owner']})));
await test('like duplicate UID denied',()=>no(updateDoc(doc(db('owner'),'itlab_posts/p'),{likes:3,likedBy:['other','owner','owner']})));
await test('like own removal allowed',()=>yes(updateDoc(doc(db('other'),'itlab_posts/p'),{likes:0,likedBy:[]})));
await test('standalone comment count change denied',()=>no(updateDoc(doc(db('owner'),'itlab_posts/p'),{commentCount:1})));
const comment=(authorId,extra={})=>({postId:'atomic',content:'Comment',authorId,authorName:'Synthetic User',authorAvatar:'',createdAt:serverTimestamp(),...extra});
const addComment=async(uid,id,count,extra={})=>{const d=db(uid),b=writeBatch(d);b.set(doc(d,'itlab_comments/'+id),comment(uid,extra));b.update(doc(d,'itlab_posts/atomic'),{commentCount:count,lastCommentId:id});return b.commit();};
const removeComment=async(uid,id,count)=>{const d=db(uid),b=writeBatch(d);b.delete(doc(d,'itlab_comments/'+id));b.update(doc(d,'itlab_posts/atomic'),{commentCount:count,lastCommentId:id});return b.commit();};
await seed({'itlab_posts/atomic':post});
await test('atomic comment create/count increment allowed',()=>yes(addComment('other','atomic1',1)));
await test('standalone comment create denied',()=>no(setDoc(doc(db('other'),'itlab_comments/standalone'),comment('other'))));
await test('standalone comment delete denied',()=>no(deleteDoc(doc(db('other'),'itlab_comments/atomic1'))));
await test('standalone count with existing comment denied',()=>no(updateDoc(doc(db('other'),'itlab_posts/atomic'),{commentCount:2,lastCommentId:'atomic1'})));
await test('atomic forged comment author denied',()=>no(addComment('other','forgedauthor',2,{authorId:'owner'})));
await test('atomic incorrect increment denied',()=>no(addComment('other','wrongcount',3)));
await test('atomic unrelated delete denied',()=>no(removeComment('new','atomic1',0)));
await test('atomic comment author delete allowed',()=>yes(removeComment('other','atomic1',0)));
await test('atomic create another comment',()=>yes(addComment('other','atomic2',1)));
await test('post owner cannot delete others comment without post marker',()=>no(removeComment('owner','atomic2',0)));
await test('nonempty post owner direct delete denied',()=>no(deleteDoc(doc(db('owner'),'itlab_posts/atomic'))));
await test('nonempty post admin direct delete denied',()=>no(deleteDoc(doc(db('admin'),'itlab_posts/atomic'))));
await test('post owner sets cascade marker',()=>yes(updateDoc(doc(db('owner'),'itlab_posts/atomic'),{deleting:true})));
await test('marked nonempty post direct delete denied',()=>no(deleteDoc(doc(db('owner'),'itlab_posts/atomic'))));
await test('atomic post owner deletes others comment during cascade',()=>yes(removeComment('owner','atomic2',0)));
await test('marked empty post owner delete allowed',()=>yes(deleteDoc(doc(db('owner'),'itlab_posts/atomic'))));
await seed({'itlab_posts/atomic':post});
await test('unmarked empty post direct delete denied',()=>no(deleteDoc(doc(db('owner'),'itlab_posts/atomic'))));
await test('atomic parent comment created',()=>yes(addComment('other','parent',1)));
await test('atomic reply created',()=>yes(addComment('new','reply',2,{parentId:'parent',replyTo:'Synthetic User'})));
await test('parent author cannot delete reply without marker',()=>no(removeComment('other','reply',1)));
await test('parent author marks parent first',()=>yes(updateDoc(doc(db('other'),'itlab_comments/parent'),{deleting:true,deletingBy:'other'})));
await test('atomic parent author deletes other reply',()=>yes(removeComment('other','reply',1)));
await test('atomic category moderator deletes comment',()=>yes(removeComment('mod','parent',0)));
await test('atomic comment create/count persisted',async()=>{const snap=await getDoc(doc(db(),'itlab_posts/atomic'));if(snap.data().commentCount!==0)throw Error('count expected zero');});
await test('deleting flag stranger denied',()=>no(updateDoc(doc(db('other'),'itlab_posts/atomic'),{deleting:true})));
await test('create comment before deletion flag',()=>yes(addComment('other','cleanup',1)));
await test('deleting flag authorized owner allowed',()=>yes(updateDoc(doc(db('owner'),'itlab_posts/atomic'),{deleting:true})));
await test('comment on deleting post denied',()=>no(addComment('other','duringdelete',2)));
await test('deleting post still permits paired cleanup',()=>yes(removeComment('owner','cleanup',0)));
await seed({'itlab_posts/atomic':post});
await test('nested root created',()=>yes(addComment('other','rootdeep',1)));
await test('nested child created',()=>yes(addComment('new','childdeep',2,{parentId:'rootdeep'})));
await test('nested grandchild created',()=>yes(addComment('new','granddeep',3,{parentId:'childdeep'})));
const mark=(uid,id)=>updateDoc(doc(db(uid),'itlab_comments/'+id),{deleting:true,deletingBy:uid});
await test('nested unrelated root marker denied',()=>no(mark('new','rootdeep')));
await test('nested unauthorized grandchild marker denied before chain',()=>no(mark('other','granddeep')));
await test('nested root author marker allowed',()=>yes(mark('other','rootdeep')));
await test('reply to deleting comment denied',()=>no(addComment('new','duringnested',4,{parentId:'rootdeep'})));
await test('nested child marker inherited allowed',()=>yes(mark('other','childdeep')));
await test('nested grandchild marker inherited allowed',()=>yes(mark('other','granddeep')));
await test('nested marker cannot alter author',()=>no(updateDoc(doc(db('other'),'itlab_comments/granddeep'),{deleting:true,deletingBy:'other',authorId:'other'})));
await test('nested deepest paired delete allowed',()=>yes(removeComment('other','granddeep',2)));
await test('nested child paired delete allowed',()=>yes(removeComment('other','childdeep',1)));
await test('nested root paired delete allowed',()=>yes(removeComment('other','rootdeep',0)));
await seed({'itlab_invitations/ATOMIC':{code:'ATOMIC',type:'chat',isUsed:false,createdBy:'admin',createdAt:new Date()}});
await test('atomic invite claim/access/profile allowed',async()=>{const d=db('new'),b=writeBatch(d);b.update(doc(d,'itlab_invitations/ATOMIC'),{isUsed:true,usedBy:'new',usedAt:serverTimestamp()});b.set(doc(d,'itlab_chat_access/new'),{userId:'new',usedCode:'ATOMIC',authorizedAt:serverTimestamp()});b.update(doc(d,'itlab_users/new'),{chatAuthorized:true});await yes(b.commit());});
await test('admin revokes grant and profile authorization',async()=>{const d=db('admin'),b=writeBatch(d);b.delete(doc(d,'itlab_chat_access/new'));b.update(doc(d,'itlab_users/new'),{chatAuthorized:false});await yes(b.commit());});
await test('revoked chat cannot read messages',()=>no(getDoc(doc(db('new'),'itlab_chat_messages/m'))));
await test('used invite standalone replay cannot recreate grant',()=>no(setDoc(doc(db('new'),'itlab_chat_access/new'),{userId:'new',usedCode:'ATOMIC',authorizedAt:serverTimestamp()})));
await test('used invite atomic replay denied',async()=>{const d=db('new'),b=writeBatch(d);b.update(doc(d,'itlab_invitations/ATOMIC'),{isUsed:true,usedBy:'new',usedAt:serverTimestamp()});b.set(doc(d,'itlab_chat_access/new'),{userId:'new',usedCode:'ATOMIC',authorizedAt:serverTimestamp()});b.update(doc(d,'itlab_users/new'),{chatAuthorized:true});await no(b.commit());});
await test('revoked profile self-authorization denied',()=>no(updateDoc(doc(db('new'),'itlab_users/new'),{chatAuthorized:true})));
await seed({'itlab_invitations/TESTCODE':{code:'TESTCODE',type:'chat',isUsed:false,createdBy:'admin',createdAt:new Date()}});
await test('invite anonymous read denied',()=>no(getDoc(doc(db(),'itlab_invitations/TESTCODE'))));
await test('invite authenticated lookup allowed',()=>yes(getDoc(doc(db('other'),'itlab_invitations/TESTCODE'))));
await test('invite ordinary list denied',()=>no(getDocs(collection(db('other'),'itlab_invitations'))));
await test('invite ordinary create denied',()=>no(setDoc(doc(db('other'),'itlab_invitations/FORGED'),{code:'FORGED',type:'chat',isUsed:false,createdBy:'other',createdAt:serverTimestamp()})));
await test('chat unauthorized read denied',()=>no(getDoc(doc(db('other'),'itlab_chat_messages/m'))));
await test('chat access forged before claim denied',()=>no(setDoc(doc(db('other'),'itlab_chat_access/other'),{userId:'other',usedCode:'TESTCODE',authorizedAt:serverTimestamp()})));
await test('standalone invite claim denied',()=>no(updateDoc(doc(db('other'),'itlab_invitations/TESTCODE'),{isUsed:true,usedBy:'other',usedAt:serverTimestamp()})));
await test('invite reuse denied',()=>no(updateDoc(doc(db('owner'),'itlab_invitations/TESTCODE'),{isUsed:true,usedBy:'owner',usedAt:serverTimestamp()})));
await test('chat access forged from another claim denied',()=>no(setDoc(doc(db('owner'),'itlab_chat_access/owner'),{userId:'owner',usedCode:'TESTCODE',authorizedAt:serverTimestamp()})));
await test('atomic second invite/access grant allowed',async()=>{const d=db('other'),b=writeBatch(d);b.update(doc(d,'itlab_invitations/TESTCODE'),{isUsed:true,usedBy:'other',usedAt:serverTimestamp()});b.set(doc(d,'itlab_chat_access/other'),{userId:'other',usedCode:'TESTCODE',authorizedAt:serverTimestamp()});await yes(b.commit());});
await test('chat access private from stranger',()=>no(getDoc(doc(db('owner'),'itlab_chat_access/other'))));
await test('chat self authorize after valid access allowed',()=>yes(updateDoc(doc(db('other'),'itlab_users/other'),{chatAuthorized:true})));
for(const uid of ['other','admin','mod'])await test('chat authorized '+uid+' read allowed',()=>yes(getDoc(doc(db(uid),'itlab_chat_messages/m'))));
const message=uid=>({userId:uid,userName:'Synthetic User',userAvatar:'',content:'hello',createdAt:serverTimestamp()});
await test('chat authorized send allowed',()=>yes(setDoc(doc(db('other'),'itlab_chat_messages/new'),message('other'))));
await test('chat impersonated send denied',()=>no(setDoc(doc(db('other'),'itlab_chat_messages/spoof'),message('admin'))));
await test('chat message edit denied',()=>no(updateDoc(doc(db('other'),'itlab_chat_messages/new'),{content:'change'})));
await seed({'itlab_settings/general':{postPermission:'all',chatEnabled:false}});
await test('chat disabled read denied even admin',()=>no(getDoc(doc(db('admin'),'itlab_chat_messages/m'))));
await test('chat disabled send denied',()=>no(setDoc(doc(db('other'),'itlab_chat_messages/disabled'),message('other'))));
for(const uid of [null,'owner','admin']){
 await test('unknown collection read denied '+uid,()=>no(getDoc(doc(db(uid),'unknown_collection/test'))));
 await test('unknown collection write denied '+uid,()=>no(setDoc(doc(db(uid),'unknown_collection/test'),{value:true})));
}
}finally{await env.cleanup();}
console.log(JSON.stringify({passed,failed}));process.exitCode=failed?1:0;
